### ISSUE TITLE
Generate default JSON object from JSON schema

### ISSUE THREAD

**Issue by awag72** [gregsdennis/Manatee.Json#279] opened 2020-07-22 18:49 UTC
Is it possible to generate a JSON object with default values from a JSON schema?

eg:
use schema:
```
{
    "title": "master data",
    "type": "object",
    "properties": {

        "Base": {
            "title": "base data",
            "type": "object",
            "options": {
                "collapsed": true
            },
            "properties": {
                "Value1": { "type": "number", "default": 1.1, "minimum": 0, "maximum": 1000, "title": "Value 1" },
                "Value2": { "type": "number", "default": 2.2, "minimum": 0, "maximum": 1000, "title": "Value 2" },
                "Value3": { "type": "number", "default": 3.3, "minimum": 0, "maximum": 1000, "title": "Value 3" }
			}
		}
	}
}
```
to produce valid JSON with default values:
```
{
	"Base": {
		"Value1": 1.1,
		"Value2": 2.2,
		"Value3": 3.3
	}
}

```

The actual schemas are more complex - also with array definitions and default array values - used for [https://github.com/json-editor/json-editor](https://github.com/json-editor/json-editor)
thx

**Comment by gregsdennis** [comment] 2020-07-22 19:24
I looked at doing this (and generating a schema from a type) back when draft 6 was the latest.  It gets really complex pretty quickly.  It's the `*Of` and `not` keywords mostly that make things difficult.

I'll add this as a feature request, though, and have a look at it again.

**Comment by gregsdennis** [comment] 2020-07-22 19:28
This also gave me an idea: #280.

**Comment by gregsdennis** [comment] 2020-07-26 13:03
Looks like this is a duplicate of #12.

**Closed by gregsdennis** 2020-07-26 13:03 UTC
Labels: feature
